version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /app
    environment:
      DATABASE_URL: mysql://u_BLsar0:KYlTQHlEhQnD@db:3306/freedb_OPB9bHFa
      DB_CONNECTION: mysql
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: freedb_OPB9bHFa
      MYSQL_USER: u_BLsar0
      MYSQL_PASSWORD: KYlTQHlEhQnD
      MYSQL_ROOT_PASSWORD: KYlTQHlEhQnD
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: